---
#- hosts: localhost:spine:leaf:host
#  gather_facts: no
#  tasks:
#    - name: remove netq
#      become: yes
#      apt:
#        name:
#          - netq-apps
#          - netq-agent
#        state: absent
- hosts: leaf:spine
  gather_facts: no
  become: yes
  tasks:
    - name: Drop the saved NVUE yaml file
      copy:
        src: lab2-configurations/{{inventory_hostname}}/config.yaml
        dest: /tmp/config.yaml
        owner: nvue
        group: nvue
        mode: 0644
      notify:
        -  nvue config patch
        -  nvue config apply
#        - netq config restart agent
  handlers:
    - name: nvue config patch
      command: nv config patch /tmp/config.yaml
    - name: nvue config apply
      command: nv config apply -y
#    - name: netq config restart agent
#      command: netq config restart agent

- hosts: host
  gather_facts: no
  tasks:
    - name: Setting up the test hosts config
      become: yes
      copy:
        src: lab2-configurations/{{inventory_hostname}}/config.yaml
        dest: /etc/netplan/config.yaml
      notify: apply interface config

    - name: install traceroute
      become: yes
      apt:
        name: traceroute
        state: present
                
    - name: flush arp
      become: yes
      command: ip -s -s neigh flush all
      no_log: true

  handlers:
    - name: apply interface config
      become: yes
      command: netplan apply
