- set:
    bridge:
      domain:
        br_default:
          vlan:
            '20': {}
    router:
      bgp:
        enable: on
      vrr:
        enable: on
    system:
      hostname: leaf02
    vrf:
      default:
        router:
          bgp:
            address-family:
              ipv4-unicast:
                enable: on
                network:
                  10.0.20.0/24: {}
                  10.255.255.2/32: {}
            autonomous-system: 65102
            enable: on
            neighbor:
              swp51:
                remote-as: external
                type: unnumbered
            path-selection:
              multipath:
                aspath-ignore: on
            router-id: 10.255.255.2
    interface:
      lo:
        ip:
          address:
            10.255.255.2/32: {}
        type: loopback
      swp2:
        bridge:
          domain:
            br_default:
              access: 20
      swp2,51:
        type: swp
      swp51:
        link:
          state:
            up: {}
      vlan20:
        ip:
          address:
            10.0.20.3/24: {}
          vrr:
            address:
              10.0.20.1/24: {}
            enable: on
            mac-address: 00:00:00:00:1a:20
            state:
              up: {}
        type: svi
        vlan: 20

