- set:
    bridge:
      domain:
        br_default:
          vlan:
            '10': {}
    router:
      bgp:
        enable: on
      vrr:
        enable: on
    system:
      hostname: leaf01
    vrf:
      default:
        router:
          bgp:
            address-family:
              ipv4-unicast:
                enable: on
                network:
                  10.0.10.0/24: {}
                  10.255.255.1/32: {}
            autonomous-system: 65101
            enable: on
            neighbor:
              swp51:
                remote-as: external
                type: unnumbered
            path-selection:
              multipath:
                aspath-ignore: on
            router-id: 10.255.255.1
    interface:
      lo:
        ip:
          address:
            10.255.255.1/32: {}
        type: loopback
      swp1:
        bridge:
          domain:
            br_default:
              access: 10
      swp1,51:
        type: swp
      swp51:
        link:
          state:
            up: {}
      vlan10:
        ip:
          address:
            10.0.10.2/24: {}
          vrr:
            address:
              10.0.10.1/24: {}
            enable: on
            mac-address: 00:00:00:00:1a:10
            state:
              up: {}
        type: svi
        vlan: 10

