- set:
    bridge:
      domain:
        br_default:
          vlan:
            '20': {}
    router:
      vrr:
        enable: on
    system:
      aaa:
        class:
          nvapply:
            action: allow
            command-path:
              /:
                permission: all
          nvshow:
            action: allow
            command-path:
              /:
                permission: ro
          sudo:
            action: allow
            command-path:
              /:
                permission: all
        role:
          nvue-admin:
            class:
              nvapply: {}
          nvue-monitor:
            class:
              nvshow: {}
          system-admin:
            class:
              nvapply: {}
              sudo: {}
        user:
          cumulus:
            full-name: cumulus,,,
            hashed-password: $5$.bZqNaSoq2PqQPCV$LKR8zu5u7whr1F8YRLYtOrO7NaF9kE7EEHw.ER3ylO4
            role: system-admin
        global:
          system-mac: 44:38:39:22:01:c1
      hostname: leaf02
    interface:
      lo:
        ip:
          address:
            10.255.255.2/32: {}
        type: loopback
      swp2:
        bridge:
          domain:
            br_default:
              access: 20
        type: swp
      vlan20:
        ip:
          address:
            10.0.20.3/24: {}
          vrr:
            address:
              10.0.20.1/24: {}
            mac-address: 00:00:00:00:1a:20
            enable: on
            state:
              up: {}
        type: svi
        vlan: 20
