- set:
    bridge:
      domain:
        br_default:
          vlan:
            '10': {}
            '20': {}
    router:
      vrr:
        enable: on
    system:
      aaa:
        class:
          nvapply:
            action: allow
            command-path:
              /:
                permission: all
          nvshow:
            action: allow
            command-path:
              /:
                permission: ro
          sudo:
            action: allow
            command-path:
              /:
                permission: all
        role:
          nvue-admin:
            class:
              nvapply: {}
          nvue-monitor:
            class:
              nvshow: {}
          system-admin:
            class:
              nvapply: {}
              sudo: {}
        user:
          cumulus:
            full-name: cumulus,,,
            hashed-password: $5$.bZqNaSoq2PqQPCV$LKR8zu5u7whr1F8YRLYtOrO7NaF9kE7EEHw.ER3ylO4
            role: system-admin
        global:
          system-mac: 44:38:39:22:01:c0
      hostname: leaf01
    interface:
      eth0:
        ip:
          address:
            dhcp: {}
          vrf: mgmt
        type: eth
      bond0:
        bond:
          member:
            swp49: {}
            swp50: {}
        bridge:
          domain:
            br_default: {}
        type: bond
      lo:
        ip:
          address:
            10.255.255.1/32: {}
        type: loopback
      swp1:
        bridge:
          domain:
            br_default:
              access: 10
        type: swp
      vlan10:
        ip:
          address:
            10.0.10.2/24: {}
          vrr:
            address:
              10.0.10.1/24: {}
            mac-address: 00:00:00:00:1a:10
        vlan: 10
      vlan10,20:
        ip:
          vrr:
            enable: on
            state:
              up: {}
        type: svi
      vlan20:
        ip:
          address:
            10.0.20.2/24: {}
          vrr:
            address:
              10.0.20.1/24: {}
            mac-address: 00:00:00:00:1a:20
        vlan: 20

