################################################################
# IMPORTANT: When using NVIDIA Air services,                   #
#  your Internet-facing interface must include the following:  #
#   dhcp6: false                                               #
#   accept-ra: true                                            #
################################################################
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: true
    eth1:
      addresses:
        - 10.0.10.101/24
      routes:
        - to: 10.0.0.0/8
          via: 10.0.10.1